export const projects = [
  {
    title: "Paletto",
    meta: "Color palette tool",
    desc: "Generate beautiful OKLCH color palettes without the Coolors paywall. Extract from any image, apply harmony schemes and mood profiles, drag to reorder, and share via URL.",
    stack: [
      "Next.js",
      "TypeScript",
      "Zustand",
      "dnd-kit",
      "SCSS Modules",
      "chroma-js",
    ],
    cover: "/img/paletto.png",
    path: "paletto",
    url: "https://palettocolors.netlify.app",
  },
  {
    title: "Blendify",
    meta: "Music discovery tool",
    desc: "Blendify is a minimal discovery tool for premium Spotify users who want a deeper dive into their listening habits.",
    stack: ["Spotify API", "Next.js", "Figma", "Product Design"],
    cover: "/img/blendify.png",
    path: "blendify",
    url: "https://blendifyv6.netlify.app/",
  },
  {
    title: "DevFolio",
    meta: "Developer portfolio",
    desc: "A sleek, modern portfolio  for me to showcase my most recent projects and skills. Built with Next.js, Figma, and a whole lot of love.",
    stack: ["Next.js", "Figma", "UI/UX Design"],
    url: "https://justinpeter.dev",
    cover: "/img/devfolio.png",
    path: "devfolio",
  },
];
