export const projects = [
  {
    title: "Paletto",
    meta: "Color palette tool",
    desc: "Generate beautiful color palettes effortlessly.",
    stack: [
      "Next.js",
      "TypeScript",
      "Zustand",
      "dnd-kit",
      "SCSS Modules",
      "chroma-js",
    ],
    cover: "/img/paletto.png",
    path: "paletto",
    url: "https://palettocolors.netlify.app",
  },
  {
    title: "Blendify",
    meta: "Music discovery tool",
    desc: "A musicdiscovery tool for Spotify users.",
    stack: ["Spotify API", "Next.js", "Figma", "Product Design"],
    cover: "/img/blendify.png",
    path: "blendify",
    url: "https://blendifyv6.netlify.app/",
  },
  {
    title: "DevFolio",
    meta: "Developer portfolio",
    desc: "Modern portfolio to showcase projects & skills.",
    stack: ["Next.js", "Figma", "UI/UX Design"],
    url: "https://justinpeter.dev",
    cover: "/img/devfolio.png",
    path: "devfolio",
  },
];
